<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <FtdGamePath Condition="'$(FtdGamePath)' == ''">D:\Program Files (x86)\Steam\steamapps\common\From The Depths</FtdGamePath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Core" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\Core.dll" />
    <Reference Include="Modding" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\Modding.dll" />
  </ItemGroup>
</Project>
