<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <FtdGamePath Condition="'$(FtdGamePath)' == ''">D:\Program Files (x86)\Steam\steamapps\common\From The Depths</FtdGamePath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Core" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\Core.dll" />
    <Reference Include="Ftd" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\Ftd.dll" />
    <Reference Include="Modding" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\Modding.dll" />
    <Reference Include="Ui" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\Ui.dll" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\UnityEngine.CoreModule.dll" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\UnityEngine.IMGUIModule.dll" />
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\UnityEngine.InputLegacyModule.dll" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\UnityEngine.TextRenderingModule.dll" />
    <Reference Include="UnityEngine.UI" HintPath="$(FtdGamePath)\From_The_Depths_Data\Managed\UnityEngine.UI.dll" />
  </ItemGroup>
</Project>
